[package]
name = "greeter"
version = "0.1.0"
edition = "2024"

[dependencies]
alpm = "5.0.0"
rand = "0.9.2"
tokio = { version = "1.37", features = ["full"] }
zbus = { version = "5.12", default-features = false, features = ["tokio"] }
